"""
Ontology generation service
Interface 1: Analyze text content and generate entity and relationship type definitions suitable for social simulation
"""

import json
from typing import Dict, Any, List, Optional
from ..utils.llm_client import LLMClient


# System prompt words generated by ontology
ONTOLOGY_SYSTEM_PROMPT = """You are a professional knowledge graph ontology design expert. Your task is to analyze the given text content and simulation requirements, and design entity types and relationship types suitable for **Social Media Opinion Simulation**.

**Important: You must output valid JSON-formatted data and nothing else. **

## Core mission background

We are building a **social media public opinion simulation system**. In this system:
- Each entity is an "account" or "subject" that can speak, interact, and spread information on social media
- Entities will influence, forward, comment, and respond to each other
- We need to simulate the reactions of all parties and information dissemination paths in public opinion events

Therefore, the **entity must be a real entity that exists in reality and can speak and interact on social media**:

**can be**:
- Specific individuals (public figures, parties, opinion leaders, experts and scholars, ordinary people)
- Companies and enterprises (including their official accounts)
- Organizational institutions (universities, associations, NGOs, trade unions, etc.)
- Government departments, regulatory agencies
- Media organizations (newspapers, TV stations, self-media, websites)
- The social media platform itself
- Representatives of specific groups (such as alumni associations, fan groups, rights protection groups, etc.)

**cannot be**:
- Abstract concepts (such as "public opinion", "sentiment", "trend")
- Theme/Topic (e.g. "Academic Integrity", "Education Reform")
- Opinions/attitudes (e.g. "supporters", "opponents")

## Output format

Please output JSON format, including the following structure:

```json
{
    "entity_types": [
        {
            "name": "Entity type name (English, PascalCase)",
            "description": "Short description (English, no more than 100 characters)",
            "attributes": [
                {
                    "name": "Attribute name (English, snake_case)",
                    "type": "text",
                    "description": "Property description"
                }
            ],
            "examples": ["Example Entity 1", "Example Entity 2"]
        }
    ],
    "edge_types": [
        {
            "name": "Relationship type name (English, UPPER_SNAKE_CASE)",
            "description": "Short description (English, no more than 100 characters)",
            "source_targets": [
                {"source": "source entity type", "target": "target entity type"}
            ],
            "attributes": []
        }
    ],
    "analysis_summary": "A brief analysis of the text content (Chinese)"
}
```

## Design Guidelines (extremely important!)

### 1. Entity type design - must be strictly followed

**Quantity requirement: There must be exactly 10 entity types**

**Hierarchy requirements (must contain both concrete types and abstract types)**:

Your 10 entity types must contain the following levels:

A. **Backup type (must be included, placed at the last 2 in the list)**:
   - `Person`: The cover type of any natural person. A person is classified into this category when he does not fit into any of the other more specific character types.
   - `Organization`: The backbone type of any organization. An organization is classified into this category when it does not belong to another more specific organization type.

B. **Specific types (8, designed according to text content)**:
   - Design more specific types for the main characters appearing in the text
   - For example: if the text involves academic events, you can have `Student`, `Professor`, `University`
   - For example: if the text involves business events, it can have `Company`, `CEO`, `Employee`

**Why do you need a cover-up type**:
- Various characters will appear in the text, such as "primary and secondary school teachers", "passerby", "a certain netizen"
- If there is no specific type matching, they should be classified as `Person`
- Similarly, small organizations, temporary groups, etc. should be classified into `Organization`

**Type-specific design principles**:
- Identify frequently occurring or key character types from the text
- Each concrete type should have clear boundaries to avoid overlap
- description must clearly explain the difference between this type and the cover-up type

### 2. Relationship type design

- Quantity: 6-10 pcs
- Relationships should reflect real connections in social media interactions
- Make sure the relationship's source_targets cover the entity types you define

### 3. Attribute design

- 1-3 key attributes per entity type
- **Note**: Attribute names cannot use `name`, `uuid`, `group_id`, `created_at`, `summary` (these are system reserved words)
- Recommended to use: `full_name`, `title`, `role`, `position`, `location`, `description`, etc.

## Entity type reference

**Individual Human (Specific)**:
- Student: student
- Professor: professor/scholar
- Journalist: reporter
- Celebrity: Celebrity/Internet Celebrity
- Executive: executive
- Official: government official
- Lawyer: lawyer
- Doctor: doctor

**Individual human being (confidence)**:
- Person: any natural person (used when it does not fall into the above specific types)

**Organization type (specific)**:
- University: university
- Company: company enterprise
- GovernmentAgency: Government agency
- MediaOutlet: media agency
- Hospital: hospital
- School: primary and secondary schools
- NGO: non-governmental organization

**Organization type (covering the bottom line)**:
- Organization: any organizational structure (used when it does not fall into the specific types above)

##Relationship type reference

- WORKS_FOR: works on
- STUDIES_AT: Studied at
- AFFILIATED_WITH: affiliated with
- REPRESENTS: Representatives
- REGULATES: Regulations
- REPORTS_ON: reports
- COMMENTS_ON: Comments
- RESPONDS_TO: responses
- SUPPORTS: support
- OPPOSES: Objection
- COLLABORATES_WITH: Cooperation
- COMPETES_WITH: competition
"""


class OntologyGenerator:
    """
    ontology generator
    Analyze text content and generate entity and relationship type definitions
    """
    
    def __init__(self, llm_client: Optional[LLMClient] = None):
        self.llm_client = llm_client or LLMClient()
    
    def generate(
        self,
        document_texts: List[str],
        simulation_requirement: str,
        additional_context: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Generate ontology definition
        
        Args:
            document_texts: document text list
            simulation_requirement: simulation requirement description
            additional_context: additional context
            
        Returns:
            Ontology definition (entity_types, edge_types, etc.)
        """
        # Build user message
        user_message = self._build_user_message(
            document_texts, 
            simulation_requirement,
            additional_context
        )
        
        messages = [
            {"role": "system", "content": ONTOLOGY_SYSTEM_PROMPT},
            {"role": "user", "content": user_message}
        ]
        
        # Call LLM
        result = self.llm_client.chat_json(
            messages=messages,
            temperature=0.3,
            max_tokens=4096
        )
        
        # Verification and post-processing
        result = self._validate_and_process(result)
        
        return result
    
    # The maximum length of text passed to LLM (50,000 words)
    MAX_TEXT_LENGTH_FOR_LLM = 50000
    
    def _build_user_message(
        self,
        document_texts: List[str],
        simulation_requirement: str,
        additional_context: Optional[str]
    ) -> str:
        """Build user message"""
        
        # Merge text
        combined_text = "\n\n---\n\n".join(document_texts)
        original_length = len(combined_text)
        
        # If the text exceeds 50,000 words, truncate it (only affects the content passed to LLM, not the map construction)
        if len(combined_text) > self.MAX_TEXT_LENGTH_FOR_LLM:
            combined_text = combined_text[:self.MAX_TEXT_LENGTH_FOR_LLM]
            combined_text += f"\n\n...(The original text has a total of {original_length} words, the first {self.MAX_TEXT_LENGTH_FOR_LLM} words have been intercepted for ontology analysis)..."
        
        message = f"""## Simulation requirements

{simulation_requirement}

## Document content

{combined_text}
"""
        
        if additional_context:
            message += f"""
## Additional instructions

{additional_context}
"""
        
        message += """
Please design entity types and relationship types suitable for social public opinion simulation based on the above content.

**Rules that must be followed**:
1. Exactly 10 entity types must be output
2. The last two must be disclosure types: Person (personal disclosure) and Organization (organization disclosure)
3. The first 8 are specific types designed based on text content
4. All entity types must be subjects that can speak in reality and cannot be abstract concepts.
5. Attribute names cannot use reserved words such as name, uuid, group_id, etc., use full_name, org_name, etc. instead
"""
        
        return message
    
    def _validate_and_process(self, result: Dict[str, Any]) -> Dict[str, Any]:
        """Validation and post-processing results"""
        
        # Make sure necessary fields exist
        if "entity_types" not in result:
            result["entity_types"] = []
        if "edge_types" not in result:
            result["edge_types"] = []
        if "analysis_summary" not in result:
            result["analysis_summary"] = ""
        
        # Verify entity type
        for entity in result["entity_types"]:
            if "attributes" not in entity:
                entity["attributes"] = []
            if "examples" not in entity:
                entity["examples"] = []
            # Make sure the description does not exceed 100 characters
            if len(entity.get("description", "")) > 100:
                entity["description"] = entity["description"][:97] + "..."
        
        # Verify relationship type
        for edge in result["edge_types"]:
            if "source_targets" not in edge:
                edge["source_targets"] = []
            if "attributes" not in edge:
                edge["attributes"] = []
            if len(edge.get("description", "")) > 100:
                edge["description"] = edge["description"][:97] + "..."
        
        # Zep API limitations: up to 10 custom entity types, up to 10 custom edge types
        MAX_ENTITY_TYPES = 10
        MAX_EDGE_TYPES = 10
        
        # Bottom type definition
        person_fallback = {
            "name": "Person",
            "description": "Any individual person not fitting other specific person types.",
            "attributes": [
                {"name": "full_name", "type": "text", "description": "Full name of the person"},
                {"name": "role", "type": "text", "description": "Role or occupation"}
            ],
            "examples": ["ordinary citizen", "anonymous netizen"]
        }
        
        organization_fallback = {
            "name": "Organization",
            "description": "Any organization not fitting other specific organization types.",
            "attributes": [
                {"name": "org_name", "type": "text", "description": "Name of the organization"},
                {"name": "org_type", "type": "text", "description": "Type of organization"}
            ],
            "examples": ["small business", "community group"]
        }
        
        # Check if there is already a pocket type
        entity_names = {e["name"] for e in result["entity_types"]}
        has_person = "Person" in entity_names
        has_organization = "Organization" in entity_names
        
        # The type of cover that needs to be added
        fallbacks_to_add = []
        if not has_person:
            fallbacks_to_add.append(person_fallback)
        if not has_organization:
            fallbacks_to_add.append(organization_fallback)
        
        if fallbacks_to_add:
            current_count = len(result["entity_types"])
            needed_slots = len(fallbacks_to_add)
            
            # If there will be more than 10 after adding, some existing types need to be removed
            if current_count + needed_slots > MAX_ENTITY_TYPES:
                # Calculate how many need to be removed
                to_remove = current_count + needed_slots - MAX_ENTITY_TYPES
                # Remove from the end (keep the more important concrete types at the front)
                result["entity_types"] = result["entity_types"][:-to_remove]
            
            #Add a cover type
            result["entity_types"].extend(fallbacks_to_add)
        
        # Ultimately ensure that limits are not exceeded (defensive programming)
        if len(result["entity_types"]) > MAX_ENTITY_TYPES:
            result["entity_types"] = result["entity_types"][:MAX_ENTITY_TYPES]
        
        if len(result["edge_types"]) > MAX_EDGE_TYPES:
            result["edge_types"] = result["edge_types"][:MAX_EDGE_TYPES]
        
        return result
    
    def generate_python_code(self, ontology: Dict[str, Any]) -> str:
        """
        Convert ontology definitions into Python code (similar to ontology.py)
        
        Args:
            ontology: ontology definition
            
        Returns:
            Python code string
        """
        code_lines = [
            '"""',
            'Custom entity type definition',
            'Automatically generated by NeuroStack Crowd Intelligence Simulator for social opinion simulation',
            '"""',
            '',
            'from pydantic import Field',
            'from zep_cloud.external_clients.ontology import EntityModel, EntityText, EdgeModel',
            '',
            '',
            '# ============== Entity type definition ==============',
            '',
        ]
        
        # Generate entity type
        for entity in ontology.get("entity_types", []):
            name = entity["name"]
            desc = entity.get("description", f"A {name} entity.")
            
            code_lines.append(f'class {name}(EntityModel):')
            code_lines.append(f'    """{desc}"""')
            
            attrs = entity.get("attributes", [])
            if attrs:
                for attr in attrs:
                    attr_name = attr["name"]
                    attr_desc = attr.get("description", attr_name)
                    code_lines.append(f'    {attr_name}: EntityText = Field(')
                    code_lines.append(f'        description="{attr_desc}",')
                    code_lines.append(f'        default=None')
                    code_lines.append(f'    )')
            else:
                code_lines.append('    pass')
            
            code_lines.append('')
            code_lines.append('')
        
        code_lines.append('# ============== Relationship type definition ==============')
        code_lines.append('')
        
        # Generate relationship type
        for edge in ontology.get("edge_types", []):
            name = edge["name"]
            # Convert to PascalCase class name
            class_name = ''.join(word.capitalize() for word in name.split('_'))
            desc = edge.get("description", f"A {name} relationship.")
            
            code_lines.append(f'class {class_name}(EdgeModel):')
            code_lines.append(f'    """{desc}"""')
            
            attrs = edge.get("attributes", [])
            if attrs:
                for attr in attrs:
                    attr_name = attr["name"]
                    attr_desc = attr.get("description", attr_name)
                    code_lines.append(f'    {attr_name}: EntityText = Field(')
                    code_lines.append(f'        description="{attr_desc}",')
                    code_lines.append(f'        default=None')
                    code_lines.append(f'    )')
            else:
                code_lines.append('    pass')
            
            code_lines.append('')
            code_lines.append('')
        
        # Generate type dictionary
        code_lines.append('# ============== Type configuration ==============')
        code_lines.append('')
        code_lines.append('ENTITY_TYPES = {')
        for entity in ontology.get("entity_types", []):
            name = entity["name"]
            code_lines.append(f'    "{name}": {name},')
        code_lines.append('}')
        code_lines.append('')
        code_lines.append('EDGE_TYPES = {')
        for edge in ontology.get("edge_types", []):
            name = edge["name"]
            class_name = ''.join(word.capitalize() for word in name.split('_'))
            code_lines.append(f'    "{name}": {class_name},')
        code_lines.append('}')
        code_lines.append('')
        
        # Generate edge source_targets mapping
        code_lines.append('EDGE_SOURCE_TARGETS = {')
        for edge in ontology.get("edge_types", []):
            name = edge["name"]
            source_targets = edge.get("source_targets", [])
            if source_targets:
                st_list = ', '.join([
                    f'{{"source": "{st.get("source", "Entity")}", "target": "{st.get("target", "Entity")}"}}'
                    for st in source_targets
                ])
                code_lines.append(f'    "{name}": [{st_list}],')
        code_lines.append('}')
        
        return '\n'.join(code_lines)

